# Awesome Self-Hosted Website Generator Configuration

# =============================================================================
# SITE METADATA
# =============================================================================
site:
  title: "Awesome Selfhosted"
  description: "Discover and explore selfhosted applications"
  url: "https://awesome-selfhosted.net"
  author: "awesome selfhosted community"
  base_path: "" # Leave empty for root, or set to "/awesome-selfhosted" for subdirectory

# =============================================================================
# DATA SOURCES
# =============================================================================
data:
  data_dir: "awesome-selfhosted-data"
  software_dir: "software"
  categories_dir: "tags"
  platforms_dir: "platforms"
  licenses_file: "licenses.yml"
  licenses_nonfree_file: "licenses-nonfree.yml"

# =============================================================================
# BUILD SETTINGS
# =============================================================================
build:
  output_dir: "output"
  template_dir: "templates"
  static_dir: "static"
  data_cache_dir: "data"

generation:
  items_per_page: 60
  enable_search_index: true
  minify_html: false
  generate_sitemap: true
  enable_pagination: true
  use_git_data: true

# =============================================================================
# UI CONFIGURATION
# =============================================================================
ui:
  # Page title formatting
  title_format: "{page_title} - {site_title}"
  title_separator: " - "

  # Banner configuration
  banner:
    enabled: false
    dismissible: true
    style: "info"  # info, warning, success, announcement
    text: "**New Release!** Check out our latest features and improvements" # Markdown bold (**text**) is supported
    button:
      text: "Release Notes"
      url: "https://github.com/awesome-selfhosted/awesome-selfhosted/releases" # this can also be "/browse.html" if external is set to false
      external: true

  # Content limits for different sections
  limits:
    homepage_popular_apps: 8
    homepage_recently_updated: 8
    homepage_random_picks: 6
    homepage_category_stats: 8
    homepage_alternatives: 6
    related_apps: 6
    browse_max_categories_per_card: 2
    browse_max_platforms_per_card: 3
    alternatives_max_categories_per_card: 2
    alternatives_max_platforms_per_card: 3

  # Text truncation settings
  truncation:
    default_description_length: 150
    homepage_description_length: 70
    browse_description_length: 90
    browse_description_full: false
    alternatives_description_length: 90
    alternatives_description_full: false
    related_apps_description_length: 100

  # Homepage configuration
  homepage:
    include_nonfree: false
    sections:
      - hero
      - popular_apps
      - recently_updated
      - random_picks
      - alternatives
      - popular_categories
      - statistics
      - footer_markdown

  # Footer markdown exclusions
  footer_markdown:
    exclude_sections:
      - "Anti-features"
      - "Contributing"
      # - "External Links"
      # - "License"

# =============================================================================
# HERO SECTION
# =============================================================================
hero:
  title: "Awesome Selfhosted"
  subtitle: "Discover amazing selfhosted Applications"
  description: 'Self-hosting is the practice of hosting and managing applications on your own server(s) instead of consuming from <a href="https://www.gnu.org/philosophy/who-does-that-server-really-serve.html">SaaSS</a> providers. This is a list of <a href="https://en.wikipedia.org/wiki/Free_software">Free Software</a> <a href="https://en.wikipedia.org/wiki/Network_service">network services</a> and <a href="https://en.wikipedia.org/wiki/Web_application">web applications</a> which can be hosted on your own server(s).'
  
  # Badges to display
  badges:
    - name: "Awesome"
      image: "/static/images/awesome.png"
      url: "https://github.com/sindresorhus/awesome"
    - name: "Dead Links Check"
      image: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/workflows/check-dead-links.yml/badge.svg"
      url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/1"
    - name: "Unmaintained Check"
      image: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/workflows/check-unmaintained-projects.yml/badge.svg"
      url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/1"
    - name: "Liberapay"
      image: "https://img.shields.io/liberapay/goal/awesome-selfhosted?logo=liberapay"
      url: "https://liberapay.com/awesome-selfhosted/"
  
  # Additional links
  links:
    - name: "GitHub Repository"
      url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
      description: "Markdown version (legacy)"
    - name: "Main Website"
      url: "https://awesome-selfhosted.net/"
      description: "Main Frontend for this dataset"
    - name: "Contributing Guide"
      url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md"
      description: "How to contribute to this project"
  
  # Call to action buttons
  cta_buttons:
    - name: "Browse All Applications"
      url: "/browse.html"
      style: "primary"
      icon: "grid"

# =============================================================================
# NAVIGATION & FOOTER
# =============================================================================
navigation:
  - title: "Browse"
    url: "/browse.html"
  - title: "Alternatives"
    url: "/alternatives.html"
    enabled: "{{ alternatives.enabled }}"  # Conditional navigation
  - title: "Statistics" 
    url: "/statistics.html"

footer:
  logo_text: "{{ site.title }}"
  tagline: "{{ site.description }}"
  credit_text: "Built with ❤️ for the self-hosting community"
  footer_text: |
    Copyright © 2015-2025, the {{ site.author }}. Data from 
    <a href="https://github.com/awesome-selfhosted/awesome-selfhosted-data" class="text-primary-600 hover:text-primary-500">awesome-selfhosted-data</a>
    <br>
    <a href="https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/LICENSE" class="text-primary-600     hover:text-primary-500">Content under CC-BY-SA 3.0 license</a>

  # Footer sections
  sections:
    navigation:
      title: "Navigation"
      links:
        - title: "Home"
          url: "/"
        - title: "Browse"
          url: "/browse.html"
        - title: "Alternatives"
          url: "/alternatives.html"
          enabled: "{{ alternatives.enabled }}"  # Conditional navigation
        - title: "Statistics"
          url: "/statistics.html"

    resources:
      title: "Resources"
      links:
        - title: "GitHub"
          url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
          external: true
        - title: "Data Source"
          url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data"
          external: true
        - title: "Sitemap"
          url: "/sitemap.xml"

# =============================================================================
# PAGE METADATA
# =============================================================================
pages:
  browse:
    title: "Browse Applications"
    description: "Discover {total_applications} selfhosted applications"

  statistics:
    title: "Statistics"
    description: "Explore trends and insights from the selfhosted community"

  alternatives:
    title: "Alternative Software"
    description: "Find selfhosted alternatives to popular software"

  home:
    meta_title: "Discover Selfhosted Applications"
    meta_description: "Find the perfect selfhosted applications for your needs"

# =============================================================================
# ALTERNATIVES PAGE CONFIGURATION
# =============================================================================
alternatives:
  enabled: false  # Set to false to disable the alternatives page
  min_alternatives: 2  # Minimum number of alternatives required to show a software
  show_more_threshold: 3 # Show "Show More" button if there are more than this number of alternatives
  show_statistics: true  # Show statistics section on the page

# =============================================================================
# SEARCH CONFIGURATION
# =============================================================================
search:
  fuzzy_threshold: 0.3
  max_results: 8
  min_query_length: 3
  search_fields:
    - name
    - description
    - categories
  placeholder_text: "Search applications..."

# =============================================================================
# RELATED APPS ALGORITHM
# =============================================================================
related_apps:
  scoring:
    semantic_similarity:
      enabled: true
      max_score: 25
    categories:
      enabled: true
      points_per_match: 4
    alternatives:
      enabled: true
      points_per_match: 6
    forks:
      enabled: true
      same_parent_score: 8
    platforms:
      enabled: true
      points_per_match: 2
    license:
      enabled: true
      same_type_score: 2
    popularity:
      enabled: true
      same_tier_score: 1
    dependencies:
      enabled: true
      same_status_score: 1
  tiebreakers:
    - stars
    - name
  min_score: 3
  debug: false

# =============================================================================
# LINK BEHAVIOR
# =============================================================================
links:
  open_in_new_tab_for_internal_links: false
  open_in_new_tab_for_external_links: false

# =============================================================================
# PERFORMANCE OPTIMIZATIONS - Not implemented
# =============================================================================
performance:
  lazy_load_images: true
  generate_webp: false
  inline_critical_css: true

# =============================================================================
# SEO & ROBOTS
# =============================================================================
robots:
  generate: true
  user_agent: "*"
  allow:
    - "/"
  disallow:
    - "/static/data/"
  sitemap_url: "/sitemap.xml"
