# Awesome Self-Hosted Website Generator Configuration

site:
  title: "Awesome Selfhosted"
  description: "Discover and explore self-hosted applications"
  url: "https://awesome-selfhosted.net"
  author: "Awesome Self-Hosted Community"
  
# UI Configuration
ui:
  # Page title formatting
  title_format: "{page_title} - {site_title}"  # Format for page titles
  title_separator: " - "  # Separator between page title and site title

  # Limits for diffrent sections
  limits:
    featured_apps: 12 # Number of featured apps to show on the homepage - OLD should be removed
    recent_apps: 8 # Number of recent apps to show on the homepage - OLD should be removed
    category_stats: 12 # Number of categories to show on the homepage - OLD should be removed
    related_apps: 6 # App detail page related apps
    browse_max_tags_per_card: 2 # Browse page tags per card
    browse_max_platforms_per_card: 3 # Browse page platforms per card

  # Default text truncation lengths
  truncation:
    default_description_length: 150 # Default description length
    browse_description_length: 250 # Browse page description length 
    browse_description_full: false # Browse page show full description (overrides length)
    related_apps_description_length: 100 # Related apps description length

  # Navigation menu items
  navigation:
    - title: "Browse"
      url: "/"
    - title: "Statistics" 
      url: "/statistics.html"

  # Footer configuration
  footer:
    logo_text: "{{ site.title }}"
    tagline: "{{ site.description }}"
    credit_text: "Built with ❤️ for the self-hosting community"
    copyright_text: "Copyright © 2015-2025, the {{ site.title }} community. Data from"
    data_source_text: "awesome-selfhosted-data"
    data_source_url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data"
    license_text: "Content under CC-BY-SA 3.0 license"
    license_url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/LICENSE"

    # Footer sections
    sections:
      navigation:
        title: "Navigation"
        links:
          - title: "Home"
            url: "/"
          - title: "Statistics"
            url: "/statistics.html"

      resources:
        title: "Resources"
        links:
          - title: "GitHub"
            url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
            external: true
          - title: "Data Source"
            url: "https://github.com/awesome-selfhosted/awesome-selfhosted-data"
            external: true
          - title: "Sitemap"
            url: "/sitemap.xml"

  # Page titles and descriptions
  pages:
    browse:
      title: "Browse Applications"
      description: "Discover {total_applications} self-hosted applications"

    statistics:
      title: "Statistics"
      description: "Explore trends and insights from the self-hosted community"

    home:
      meta_title: "Discover Self-Hosted Applications"
      meta_description: "Find the perfect self-hosted applications for your needs"

# Data sources
data:
  awesome_selfhosted_data_dir: "awesome-selfhosted-data"
  software_dir: "software"
  tags_dir: "tags"
  platforms_dir: "platforms"
  licenses_file: "licenses.yml"

# Build settings
build:
  output_dir: "output"
  template_dir: "templates"
  static_dir: "static"
  data_cache_dir: "data"

# Site generation options
generation:
  items_per_page: 60
  enable_search_index: true
  minify_html: false
  generate_sitemap: true
  enable_pagination: true

# Search settings
search:
  fuzzy_threshold: 0.3
  max_results: 8
  min_query_length: 3
  search_fields:
    - name
    - description
    - tags
    - categories
  placeholder_text: "Search applications..."

related_apps:
  scoring:
    semantic_similarity:
      enabled: true
      max_score: 25
    categories:
      enabled: true
      points_per_match: 4
    alternatives:
      enabled: true
      points_per_match: 6
    forks:
      enabled: true
      same_parent_score: 8
    language:
      enabled: true
      same_language_score: 3
    platforms:
      enabled: true
      points_per_match: 2
    license:
      enabled: true
      same_type_score: 2
    popularity:
      enabled: true
      same_tier_score: 1
    dependencies:
      enabled: true
      same_status_score: 1
  tiebreakers:
    - stars
    - name
  min_score: 3
  debug: false

# Links settings
links:
  open_in_new_tab_for_internal_links: false
  open_in_new_tab_for_external_links: false

# Performance settings - Not implemented
performance:
  lazy_load_images: true
  generate_webp: false
  inline_critical_css: true

# Robots.txt settings
robots:
  generate: true
  user_agent: "*"
  allow:
    - "/"
  disallow:
    - "/static/data/"
  sitemap_url: "/sitemap.xml"