name: Bug Report
description: File a bug report for the Awesome Selfhosted Website Generator
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command '...'
        2. Navigate to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System (if generator related)
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other / Not applicable
    validations:
      required: false

  - type: input
    id: os-version
    attributes:
      label: OS Version (if generator related)
      description: Specific version of your operating system (e.g., Windows 10, Ubuntu 22.04, macOS 14)
      placeholder: e.g., Windows 10, Ubuntu 22.04
    validations:
      required: false

  - type: input
    id: python-version
    attributes:
      label: Python Version (if generator related)
      description: What version of Python are you using?
      placeholder: e.g., 3.11.0
    validations:
      required: false

  - type: input
    id: generator-version
    attributes:
      label: Generator Version/Commit (if self-hosted)
      description: What version or commit of the generator are you using?
      placeholder: e.g., main branch, commit hash, tag v1.0.0
    validations:
      required: false

  - type: input
    id: browser-version
    attributes:
      label: Browser and Version (if UI-related)
      description: Specific browser version (if applicable)
      placeholder: e.g., Chrome 120, Firefox 121
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration (if self-hosted)
      description: If relevant, please share relevant parts of your `config.yml` (remove any sensitive information)
      placeholder: |
        ```yaml
        # Relevant config sections here
        ```
      render: yaml
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all relevant information to help reproduce this issue
          required: true
