name: Feature Request / Suggestion
description: Suggest a new feature or improvement for the Awesome Selfhosted Website Generator
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature or improvement you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Currently, users face the following problem...
        This feature would solve it by...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        The feature should work like this:
        - Step 1...
        - Step 2...
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area of the project would this feature affect? (optional)
      options:
        - UI/UX
        - Data Processing
        - Configuration
        - Performance
        - Documentation
        - Templates
        - JavaScript/Client-side
        - Build System
        - Other
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, mockups, or implementation ideas (optional)
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
