name: Feature Request / Suggestion
description: Suggest a new feature or improvement for the Awesome Selfhosted Website Generator
title: "[Enhancement] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature or improvement you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, mockups, or implementation ideas (optional)
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
